// <auto-generated />
using System;
using DatabookService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DatabookService.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251104114206_AddIsCollectionField")]
    partial class AddIsCollectionField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DatabookService.Domain.Entities.DirectoryField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColumnName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("DataType")
                        .HasColumnType("integer");

                    b.Property<Guid>("DirectoryTypeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCollection")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ReferenceDirectoryTypeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DirectoryTypeId");

                    b.HasIndex("ReferenceDirectoryTypeId");

                    b.ToTable("DirectoryFields", (string)null);
                });

            modelBuilder.Entity("DatabookService.Domain.Entities.DirectoryType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TableName")
                        .IsUnique();

                    b.ToTable("DirectoryTypes", (string)null);
                });

            modelBuilder.Entity("DatabookService.Domain.Entities.DirectoryField", b =>
                {
                    b.HasOne("DatabookService.Domain.Entities.DirectoryType", "DirectoryType")
                        .WithMany("Fields")
                        .HasForeignKey("DirectoryTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DatabookService.Domain.Entities.DirectoryType", "ReferenceDirectoryType")
                        .WithMany()
                        .HasForeignKey("ReferenceDirectoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DirectoryType");

                    b.Navigation("ReferenceDirectoryType");
                });

            modelBuilder.Entity("DatabookService.Domain.Entities.DirectoryType", b =>
                {
                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
